apiVersion: v1
kind: PersistentVolume

metadata:
  name: hostpv

spec:
  capacity:
    storage: 1Gi

  volumeMode: Filesystem

  storageClassName: standard

  accessModes:
  - ReadWriteOnce

  hostPath:
    # for single node testing only; will not work in a multi node cluster, use local volume
    path: /data/
    type: DirectoryOrCreate
